{% set version = '0.1.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-monotone
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/monotone_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/monotone/monotone_{{ version }}.tar.gz
  sha256: ae06dadf4a0d2c7e2702be46f39952085529994df0ed7f6c48e21517ca4df247

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'            # [win]

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('monotone')"           # [not win]
    - "\"%R%\" -e \"library('monotone')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=monotone
  summary: The monotone package contains a fast up-and-down-blocks implementation for the pool-adjacent-violators
    algorithm for simple linear ordered monotone regression, including two spin-off
    functions for unimodal and bivariate monotone regression (see <doi:10.18637/jss.v102.c01>).
  license: GPL-3.0-only
  license_family: GPL
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - leej3

# Package: monotone
# Type: Package
# Title: Performs Monotone Regression
# Version: 0.1.2
# Authors@R: c(person(given = "Frank", family = "Busing", role = c("aut", "cre"), email = "busing@fsw.leidenuniv.nl"), person("Juan", "Claramunt Gonzalez", role = "aut", email = "j.claramunt.gonzalez@fsw.leidenuniv.nl"))
# Author: Frank Busing [aut, cre], Juan Claramunt Gonzalez [aut]
# Maintainer: Frank Busing <busing@fsw.leidenuniv.nl>
# Description: The monotone package contains a fast up-and-down-blocks implementation for the pool-adjacent-violators algorithm for simple linear ordered monotone regression, including two spin-off functions for unimodal and bivariate monotone regression (see <doi:10.18637/jss.v102.c01>).
# License: GPL-3
# Encoding: UTF-8
# RoxygenNote: 7.1.1
# NeedsCompilation: yes
# Packaged: 2022-05-25 12:15:57 UTC; jclaramunt
# Repository: CRAN
# Date/Publication: 2022-05-25 14:00:02 UTC
